### ISSUE TITLE
Background (wallpaper) not working on some Win11 devices

### ISSUE THREAD

**Issue by Ilhan75** [mtniehaus/AutopilotBranding#10]
Majority of computer will run this script and it works 100%, but lately some Windows 11 devices (not sure if touchscreen might be a factor) fail to setup background image on the user's desktop. When I look at log files it is all reported as successful. Any ideas or suggestions? THANK YOU.

**Comment by mtniehaus** [comment]
There's something odd going on in Windows -- it seems to be timing-dependent.  I will run it on the same machine/VM 10 times in a row and one of them will not display the background.

**Comment by Ilhan75** [comment]
Mike, I am impressed by how quickly you respond. THANK YOU.
I haven't noticed any issues with Windows 10 devices. This happens only on new devices that come with Windows 11 (pre-installed). I am not sure if touchscreen might be a factor for the issue.

Ilhan



Ilhan Ramic

DWS Platform Engineer
Digital Workplace Services (DWS)

 Tel. (201) 431-8498


[Pearson]
Learn more at pearson.com<http://www.pearson.com/>

________________________________

**Comment by gforal** [comment]
I have noticed the same thing... I am testing Autopilot with a USB stick I made using the Surface Deployment Accelerator and a 23H2 WIM which was patched to February 2024. I deployed the branding script as a blocking app in the ESP. 

I noticed that the DefaultUser InstallTheme value was reset sometime before the machine and user portions of enrollment. I also tried setting the "DefaultUser\Control Panel\Wallpaper" value and it was also reset to the normal img0 wallpaper. This behavior is very consistent with self-deployment.

**Comment by vdmchkv** [comment]
Hello @mtniehaus, 

I think I have an explanation for this behaviour. Analysing the issue with a brand new Lenovo device with preinstalled Windows 11 23H2, I found that the image was prepared using the sysprep method. This also includes some activities after the enrolment, which are configured using unattended install. You can locate, for example, unattended.xml under C:\Windows\Panther\ as well as in the Microsoft Documentation [here](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-themes-themename).

**Comment by vdmchkv** [comment]
As a follow-up to my post earlier today, I have implemented the following solution in my version of a similar branding script. Please consider incorporating it into yours as well. I am not creating a pull request, as I haven't had the option to test it properly.

Add function somewhere in your script. The purpose of the function is to check existence of particular value in registry
`function Test-RegistryValue {
    param (
        [parameter(Mandatory = $true)][ValidateNotNullOrEmpty()]$Path,
        [parameter(Mandatory = $true)][ValidateNotNullOrEmpty()]$Value
    )
    try {
        Get-ItemProperty -Path $Path -ErrorAction Stop | Select-Object -ExpandProperty $Value -ErrorAction Stop | Out-Null
        return $true
    }
    catch {
        return $false
    }
}`

and then delete properties from OEMs within your script where setup Theme:
`    # Remove OEM Theme and background if present
    $HKLMThemePath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes"
    if (Test-RegistryValue -Path $HKLMThemePath -Value 'BrandIcon') {
        Remove-ItemProperty -Path $HKLMThemePath -Name 'BrandIcon'  -Force
    }

    if (Test-RegistryValue -Path $HKLMThemePath -Value 'DesktopBackground') {
        Remove-ItemProperty -Path $HKLMThemePath -Name 'DesktopBackground'  -Force
    }

    if (Test-RegistryValue -Path $HKLMThemePath -Value 'ThemeName') {
        Remove-ItemProperty -Path $HKLMThemePath -Name 'ThemeName'  -Force
    }

    if (Test-RegistryValue -Path $HKLMThemePath -Value 'NoThemeInstall') {
        Remove-ItemProperty -Path $HKLMThemePath -Name 'NoThemeInstall'  -Force
    }`

**Comment by ehiusb** [comment]
Has anyone tested this to see if it works?

**Comment by Ilhan75** [comment]
No. I did not have chance to test it.



Thank you,

Ilhan



Ilhan Ramic

DWS Platform Engineer
Digital Workplace Services (DWS)

 Tel. (201) 431-8498


[Pearson]
Learn more at pearson.com<http://www.pearson.com/>

________________________________

**Comment by kcyberman17** [comment]
I am running into this issue as well. I was having weird behavior with the theme in general and almost scrapped using those settings entirely, but then I discovered that the Windows 10 theme configuration differs from the Windows 11 configuration in regards to how Dark Mode is set.

The Autopilot.theme file that is included in the script is missing at least one setting for Dark Mode. It only has `SystemMode=Dark` and should have:

`SystemMode=Dark
AppMode=Dark`

**Comment by dany20mh** [comment]
@kcyberman17 

I use this to disable Spotlight, and it's working well so far for me.

```
# Disable Windows Spotlight features
$spotlightPath = "HKLM:\TempUser\Software\Policies\Microsoft\Windows\CloudContent"
New-ItemProperty -Path $spotlightPath -Name "DisableWindowsSpotlightFeatures" -Value 1 -PropertyType DWord -Force
```
But disabling that didn't fix my issue. Even though my theme was selected as the default, a different picture was selected, and I ended up setting the default picture to the default profile.

```
# Add Wallpaper settings
$desktopPath = "HKLM:\TempUser\Control Panel\Desktop"
New-ItemProperty -Path $desktopPath -Name "WallPaper" -Value "c:\windows\web\wallpaper\MYPICTURE.png" -PropertyType String -Force
New-ItemProperty -Path $desktopPath -Name "WallpaperStyle" -Value "0" -PropertyType String -Force
```
Note. I did WallpaperStyle to 0 because I wanted to be in the Center.
Note2. Disabling Spotlight with policy in Intune helped me with an in-place upgrade from 23H2 to 24H2 to not change the picture and keep it as it is, so make sure you set that up as well.

**Comment by mtniehaus** [comment]
The changes to disable Spotlight have been merged, closing this.  If there are still issues, then it's likely a different cause so someone can open a new issue.
